{*
* 2018 Areama
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Areama <contact@areama.net>
*  @copyright  2018 Areama
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Areama
*}
<div class="arseopro-config-panel {if $activeTab != 'redirects'}hidden{/if}" id="arseopro-redirect">
    {$form->generateForm($redirectsFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
    <div class="panel">
        <div class="panel-heading show-heading">
            <i class="icon-cog"></i> {l s='List of redirects' mod='arseopro'}
            <span class="panel-heading-action">
                <a class="list-toolbar-btn" onclick="arSEO.redirect.newRule(); return false;" href="#">
                    <span title="" data-toggle="tooltip" class="label-tooltip" data-original-title="New redirect rule" data-html="true" data-placement="top">
                        <i class="process-icon-new"></i>
                    </span>
                </a>
                <a class="list-toolbar-btn" onclick="arSEO.redirect.reload(); return false;" href="#">
                    <span title="" data-toggle="tooltip" class="label-tooltip" data-original-title="Refresh list" data-html="true" data-placement="top">
                        <i class="process-icon-refresh"></i>
                    </span>
                </a>
                <a class="list-toolbar-btn" onclick="arSEO.redirect.clear(); return false;" href="#">
                    <span title="" data-toggle="tooltip" class="label-tooltip" data-original-title="Clear redirect list" data-html="true" data-placement="top">
                        <i class="process-icon-trash icon-trash"></i>
                    </span>
                </a>
            </span>
        </div>
        <div class="form-wrapper">
            <div id="form-redirect-list-container">
                <div id="form-redirect-list" class="arseo-placeholder">
                    <input type="hidden" name="page" value="1" />
                </div>
            </div>
            
            <div class="text-right">
                <button type="button" class="btn btn-success" onclick="arSEO.redirect.newRule()">
                    {l s='Create new redirect' mod='arseopro'}
                </button>
                <button type="button" class="btn btn-default" onclick="arSEO.redirect.notFoundList()">
                    {l s='Generate from page not found list' mod='arseopro'}
                </button>
                <button type="button" class="btn btn-default" onclick="arSEO.redirect.importModal()">
                    <i class="icon icon-upload"></i> {l s='Import from CSV file' mod='arseopro'}
                </button>
                <button type="button" class="btn btn-default" onclick="arSEO.redirect.export()">
                    <i class="icon icon-download"></i> {l s='Export to CSV file' mod='arseopro'}
                </button>
                <button type="button" class="btn btn-default" onclick="arSEO.redirect.clear()">
                    <i class="icon icon-trash"></i> {l s='Clear redirect list' mod='arseopro'}
                </button>
            </div>
        </div>
    </div>
</div>
{include file="./redirects/_modal.tpl"}
{include file="./redirects/_modal_nf.tpl"}
{include file="./redirects/_modal_import.tpl"}
{include file="./redirects/_modal_export.tpl"}