{*
* 2018 Areama
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Areama <contact@areama.net>
*  @copyright  2018 Areama
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Areama
*}
<div class="tab-pane {if $activeSubTab == 'ArSeoProURLProduct'}active{/if}" id="arseopro-product">
    {$form->generateForm($urlProductFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
    
    <div class="panel">
        <div class="panel-heading show-heading">
            <i class="icon-cog"></i> {l s='URL Rewrite Rules for products' mod='arseopro'}
            <span class="panel-heading-action">
                <a class="list-toolbar-btn" onclick="arSEO.url.newRule(); return false;" href="#">
                    <span title="" data-toggle="tooltip" class="label-tooltip" data-original-title="New rewrite rule" data-html="true" data-placement="top">
                        <i class="process-icon-new"></i>
                    </span>
                </a>
                <a class="list-toolbar-btn" onclick="arSEO.url.reload(); return false;" href="#">
                    <span title="" data-toggle="tooltip" class="label-tooltip" data-original-title="Refresh rules list" data-html="true" data-placement="top">
                        <i class="process-icon-refresh"></i>
                    </span>
                </a>
                <a class="list-toolbar-btn" onclick="arSEO.url.clear(); return false;" href="#">
                    <span title="" data-toggle="tooltip" class="label-tooltip" data-original-title="Clear rules list" data-html="true" data-placement="top">
                        <i class="process-icon-trash icon-trash"></i>
                    </span>
                </a>
            </span>
        </div>
        <div class="form-wrapper">
            <div id="form-url-list-container">
                <div id="form-url-list" class="arseo-placeholder">
                    <input type="hidden" name="page" value="1" />
                </div>
            </div>
            <div class="text-right">
                <button type="button" class="btn btn-success" onclick="arSEO.url.newRule()">
                    {l s='Create new rule' mod='arseopro'}
                </button>
                <button type="button" class="btn btn-primary" onclick="arSEO.url.applyRule(0, 0, 0, 1)">
                    {l s='Apply all rules' mod='arseopro'}
                </button>
                <button type="button" class="btn btn-warning" onclick="arSEO.url.clear()">
                    <i class="icon icon-trash"></i> {l s='Clear url rules list' mod='arseopro'}
                </button>
            </div>
        </div>
    </div>
</div>